services:
  db:
    container_name: shoplite_db_staging
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-shoplite_staging}
      POSTGRES_USER: ${POSTGRES_USER:-shoplite}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-shoplite_password}

  api:
    container_name: shoplite_api_staging
    environment:
      APP_VERSION: ${APP_VERSION:-staging}
      LOG_LEVEL: debug
      DATABASE_URL: postgres://${POSTGRES_USER:-shoplite}:${POSTGRES_PASSWORD:-shoplite_password}@db:5432/${POSTGRES_DB:-shoplite_staging}

  frontend:
    container_name: shoplite_frontend_staging

  proxy:
    container_name: shoplite_proxy_staging
    ports:
      - "${HTTP_PORT_STAGING:-8081}:80"
